# Generated by Django 5.1.3 on 2024-12-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_rename_ingredients_ingredient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="note",
            new_name="notes",
        ),
    ]
